;SACA POR EL PUERTO B EL VALOR 0X55
;SACA POR EL PUERTO C EL VALOR 0XAA
;SACA POR EL PUERTO D EL VALOR 0XCC


;DIRECTIVAS
			 PROCESSOR	16F887
		 	__CONFIG	0X2007,23E4
			__CONFIG	0X2008,3FFF
			INCLUDE		<P16F887.INC>

			ORG			0X0000			;EMPEZAR EN LA DIRECCION 0 DE LA MEMORIA DE PROGRAMA

;ETIQUETAS | NEMONICOS | OPERANDOS 		| COMENTARIOS			
			MOVLW		0X55
			MOVWF		PORTB
			MOVLW		0XAA
			MOVWF		PORTC
			MOVLW		0XCC
			MOVWF		PORTD
			BSF			STATUS,RP0
			BSF			STATUS,RP1		;ACCEDER AL BANCO 3
			CLRF		ANSEL
			CLRF		ANSELH			;TODOS LOS PUERTTOS DIGITALE	
			BCF			STATUS,RP1		;ACCEDEMOS AL BANCO 1
			CLRF		TRISB
			CLRF		TRISC
			CLRF		TRISD

LOOP:	
			GOTO		LOOP
			END			;DIRECTIVA END, LE AVISA AL COMPILADOR HASTA DONDE SE DEBE ENSAMBLAR