
#DEFINE V1_E	BSF	PORTE,2
#DEFINE V1_A	BCF	PORTE,2
#DEFINE A1_E	BSF PORTE,1
#DEFINE A1_A	BCF PORTE,1
#DEFINE R1_E	BSF PORTE,0
#DEFINE R1_A	BCF PORTE,0

#DEFINE V2_E	BSF PORTD,2
#DEFINE V2_A	BCF PORTD,2
#DEFINE A2_E	BSF PORTD,1
#DEFINE A2_A	BCF PORTD,1
#DEFINE R2_E	BSF PORTD,0
#DEFINE R2_A	BCF PORTD,0
