;DESCRIPCION:
;SI PB<=PC, PD = 0XDF Y PA = 0X8F
;SI PB>PC, PD = 0X34 Y PA = 0X6A

			INCLUDE		<D:\Archivos\Programacion\Microcontroladores\PIC\ASSEMBLER\MPASM\PIC16F887\00_PLANTILLA\PLANTILLA.ASM>
			;NOS DEJA EN EL BANCO 1	
			
;ETIQUETAS | NEMONICOS | OPERANDOS 		| COMENTARIOS	
			MOVLW		0XFF
			MOVWF		TRISB
			MOVWF		TRISC
			CLRF		TRISD
			CLRF		TRISA
	
		
			BCF			STATUS,RP0		;BANCO 0
			
LOOP:
			MOVF		PORTB,W			;LEER EL VALOR DE PUERTO C
			SUBWF		PORTC,W			; W = PORTC - W ( PORTB)
			BTFSS		STATUS,C		;EL RESULTADO ES POSITIVO? C==O? PB<=PC?
			GOTO        MENOR_IGUAL
			MOVLW		0XDF
			MOVWF		PORTD
			MOVLW		0X8F
			MOVWF		PORTA
			GOTO		LOOP			

			
MENOR_IGUAL:
			MOVLW		0X34
			MOVWF		PORTD
			MOVLW		0X6A
			MOVWF		PORTA
			GOTO		LOOP

			END