;DESCRIPCION:
;	LEA EL PB Y AL PC. SI PB>=PC EL PD DEBE SACAR 0X01,SI EL 
;   PB<PC, EL PUERTO D DEBE SACAR 0X80

			INCLUDE		<D:\Archivos\Programacion\Microcontroladores\PIC\ASSEMBLER\MPASM\PIC16F887\00_PLANTILLA\PLANTILLA.ASM>
			;NOS DEJA EN EL BANCO 1	
			
;ETIQUETAS | NEMONICOS | OPERANDOS 		| COMENTARIOS	
			MOVLW		0XFF
			MOVWF		TRISB			;PUERTO B COMO ENTRADA
			MOVWF		TRISC			;PUERTO C COMO ENTRADA
			
			CLRF		TRISD			;PUERTO D COMO SALIDA
			BCF			STATUS,RP0		;BANCO 0
			
LOOP:
			MOVF		PORTC,W			;LEER PUERTO C
			SUBWF		PORTB,W			;W= PORTB - W(PORTC)
			MOVLW		0X01			;0X01 -> W
			BTFSS		STATUS,C		;EL RESULTADO ES POSITIVO? (PB>=PC)
			MOVLW		0X80			;NO,(PB<PC) 0X80 -> W
			MOVWF		PORTD			;SI,W->PUERTO D
			GOTO 		LOOP
			END