;LEA EL PUERTO B Y EL PUERTO C, SUME LOS CONTENIDOS Y EL RESULTADO
;SALGA POR EL PUERTO D 

			INCLUDE		<D:\Archivos\Programacion\Microcontroladores\PIC\ASSEMBLER\MPASM\PIC16F887\00_PLANTILLA\PLANTILLA.ASM>
			;NOS DEJA EN EL BANCO 1	
			
;ETIQUETAS | NEMONICOS | OPERANDOS 		| COMENTARIOS	
			MOVLW		0XFF
			MOVWF		TRISB			;PUERTO B COMO ENTRADA
			;MOVLW		0XFF
			MOVWF		TRISC			;PUERTO C COMO ENTRADA

			CLRF		TRISD			;PUERTO D SALIDA
			BCF			STATUS,RP0		;BANCO 0
			;LOOP
			MOVF		PORTB,W			;LEER EL PUERTO B -> W
			ADDWF		PORTC,W			; W + PUERTO C
			MOVWF		PORTD			;MOVER RESULTADO AL PUERTO D
			GOTO		$-3				;REGRESAR 3 DIRECCIONES
						
			END