;DESCRIPCION:
;LEA EL PUERTO B Y AL PUERTO, SI PB=PC, EL PUERTO D DEBE SACAR PD=0X80
;SI PB ? PC, EL PD = 0X01

			INCLUDE		<D:\Archivos\Programacion\Microcontroladores\PIC\ASSEMBLER\MPASM\PIC16F887\00_PLANTILLA\PLANTILLA.ASM>
			;NOS DEJA EN EL BANCO 1	
			
;ETIQUETAS | NEMONICOS | OPERANDOS 		| COMENTARIOS	
			MOVLW		0XFF
			MOVWF		TRISB
			MOVWF		TRISC
			CLRF		TRISD
			
			BCF			STATUS,RP0
			
LOOP
			MOVF		PORTB,W
			XORWF		PORTC,W
			MOVLW		0X80
			BTFSS		STATUS,Z		;EL PUERTO B ES IGUAL AL PUERTO C?
			MOVLW		0X01			;NO, SACA EL VALOR 0X24 POR EL PUERTO D
			MOVWF		PORTD			;SI, SACA EL VALOR 0XFD POR EL PUERTO D
			GOTO		LOOP			
			END