DESCRIPCION:
;MANEJO DE 0 A F, CON INTERVADLOS DE 1 EN 1 Y TIEMPOS DE CONTEO DE 1s
;EL PUERTO QUE CONTROLA LOS DISPLAYS ES PUERTO D
;EL DISPLAY ES DE CATODO COMUN
;PARA ENCENDER EL DISPLAY SE DEBE ESCRIBIR "1" EN EL RA0
			INCLUDE		<D:\Archivos\Programacion\Microcontroladores\PIC\ASSEMBLER\MPASM\PIC16F887\LIBRERIAS\RETARDOS_MACROS.ASM> ;MACRO DE RETARDO
			INCLUDE		<D:\Archivos\Programacion\Microcontroladores\PIC\ASSEMBLER\MPASM\PIC16F887\LIBRERIAS\PLANTILLA.ASM>	;CONFIGURACION BASICA

			;NOS DEJA EN EL BANCO 1	
;----------------------------EQU-------------------------------------
CONTADOR	EQU			0X20
;---------------------------MACROS-----------------------------------
;---------------------------DEFINE-----------------------------------

;-----------------------CODIGO PRINCIPAL------------------------------
;ETIQUETAS | NEMONICOS | OPERANDOS 		| COMENTARIOS	
			CLRF		TRISD
			BCF			TRISA,0
			BCF			STATUS,RP0		;BANCO 0	
			
			BSF			PORTA,0
			CLRF		CONTADOR		;LIMPIAR EL REGISTRO CONTA
VISUALIZA:	MOVF		CONTADOR,W		;LEER EL REGISTRO CONTA
			CALL		SIETE_SEG			;DEVUELVE EN EL ACUMULADOR EL RESULTADO DE 7 SEG
			MOVWF		PORTD
			RETARDO_3V	.3,.234,.203	;RETARDO DE 1s
			INCF		CONTADOR,F		;INCREMENTAR EL CONTADOR
			MOVLW		0X0F
			ANDWF		CONTADOR,F		;CONTADOR NO SUPERE F
			GOTO		VISUALIZA
			
;			ORG			0X700			;PARA USAR PCLATH
;--------------------------SUBRUTINAS--------------------------------
;SIETE_SEG:	MOVWF		0X21
;			MOVLW		0X07
;			MOVWF		PCLATH
;			ADDWF		PCL,F
;			DT			0X3F,0X06,0X5B,0X4F,0X66,0X7D,0X07,0X7F,0X6F,0X77,0X7C,0X39,0X5E,0X79,0X71

SIETE_SEG:	ADDWF		PCL,F
			DT			0X3F,0X06,0X5B,0X4F,0X66,0X7D,0X07,0X7F,0X6F,0X77,0X7C,0X39,0X5E,0X79,0X71

;			RETLW		0X3F
;			RETLW		0X06
;			RETLW		0X5B
;			RETLW		0X4F
;			RETLW		0X66
;			RETLW		0X7D
;			RETLW		0X07
;			RETLW		0X7F
;			RETLW		0X6F
;			RETLW		0X77
;			RETLW		0X7C
;			RETLW		0X39
;			RETLW		0X5E
;			RETLW		0X79
;			RETLW		0X71

;---------------------------LIBRERIAS--------------------------------
			INCLUDE		<D:\Archivos\Programacion\Microcontroladores\PIC\ASSEMBLER\MPASM\PIC16F887\LIBRERIAS\RETARDOS.asm>
					
			END