
;ETIQUETAS | NEMONICOS | OPERANDOS 		| COMENTARIOS	

CONFIGURACION		MACRO
		
INICIALIZA:   		  	BSF			STATUS,RP0
					BSF			STATUS,RP1		;ACCEDIENDO AL BANCO 3
					CLRF		ANSEL
					CLRF		ANSELH			;TODOS LOS PINES DIGITALES
			
					BCF			STATUS,RP1
					BSF			STATUS,RP0		;ACCEDIENDO AL BANCO 1
					CLRF		TRISA			;PUERTO A COMO ENTRADA
					CLRF		TRISB			;PUERTO B COMO SALIDA
					CLRF		TRISC			;PUERTO C COMO ENTRADA
					CLRF		TRISD			;PUERTO D COMO SALIDA
					CLRF		TRISE			;PUERTO E COMO ENTRADA
			

					BCF			STATUS,RP0		
					BCF			STATUS,RP1		;ACCEDIENDO AL BANCO 0
					CLRF		PORTA			;LIMPIAR EL PUERTO A
					CLRF		PORTB			;LIMPIAR EL PUERTO B
					CLRF		PORTC			;LIMPIAR EL PUERTO C
					CLRF		PORTD			;LIMPIAR EL PUERTO D
					CLRF		PORTE			;LIMPIAR EL PUERTO E
		
					BCF			STATUS,RP1
					BSF			STATUS,RP0		;ACCEDIENDO AL BANCO 1
					ENDM	

