;DESCRIPCION:
;CALCULAS VALORES PARA CREAR UN RETARDO DE 1MS

			INCLUDE		<D:\Archivos\Programacion\Microcontroladores\PIC\ASSEMBLER\MPASM\PIC16F887\00_PLANTILLA\PLANTILLA.ASM>
			;NOS DEJA EN EL BANCO 1	
			
;ETIQUETAS | NEMONICOS | OPERANDOS 		| COMENTARIOS	
			CLRF		TRISD
			BCF			STATUS,RP0
			
LOOP:
			COMF		PORTD,F
			CALL		RETARDO_1MS
			GOTO		LOOP
						
			
			
RETARDO_1MS:						;2CY
			MOVLW		.142		;1CY
			MOVWF		0X60		;1CY
RET			NOP						
			NOP						
			NOP						
			NOP						;VAR(4NOP)
			DECFSZ		0X60,F		;3(VAR-CY)
			GOTO		RET			;2CY
			RETURN					;2CY
			END
			
			;8CY+VAR(#NOPS)+3(VAR-CY)
			;8CY+VAR(#NOPS*CY)+3VAR-3CY
			;5CY+VAR(#NOPS+3)CY
			
			;PARA FOSC=4MHz   FCY=FOSC/4  FCY=1MHZ 
			;TCY=1/FCY   TCY=1/1X10^6  TCY= 1us
			
			;PARA ESTE EJEMPLO #NOPS = 4 Y VAR=256(MAX)
			
			;NUMERO DE CICLOS = 5CY+256(4+3)CY  = 1797CY MAXIMOS
			;TIEMPO MAXIMO =1.7mS
			
			;CALCULO PARA 1us :
			;5CY+VAR(#NOPS+3)CY=1000CY -> VAR=(1000CY-5CY)/(#NOPS+3)
			;PARA ESTE EJEMPLO:
			;VAR=(1000CY-5CY)/(7) = 142,12  VAR->142 
			;TENER EN CUENTA QUE VAR PUEDE IR DE 1 A 256	
			
			;CALCULO DEL TIEMPO:
			;	5CY+142(4+3)CY	= 999CY   CY=1US 999uS = 1MS